apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-app-comosus
  labels:
    app: client-app-comosus
spec:
  selector:
    matchLabels:
        app: client-app-comosus
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: client-app-comosus
    spec:
      containers:
        - name: comosus-client
          image: 947036392937.dkr.ecr.us-east-1.amazonaws.com/comosus-client-img:latest
          ports:
            - containerPort: 3000
              protocol: TCP
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: client-app-comosus
spec:
  selector:
    app: client-app-comosus
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer